name:  decimal
author: "Alexandre Ardhuin <alexandre.ardhuin@gmail.com>"
homepage: https://github.com/a14n/dart-decimal
version: 0.0.2
description:  A simple package to deal with decimal numbers

dependencies:
  unittest: any
  meta: any
