name: decimal
version: 2.3.1
description: >
  The decimal package allows you to deal with decimal numbers without losing
  precision.
repository: https://github.com/a14n/dart-decimal
environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  rational: ^2.0.0

dev_dependencies:
  expector: ^0.1.2
  intl: ^0.17.0
  lints: ^2.0.0
  test: ^1.17.2
