name: decimal
version: 3.0.1
description: >
  The decimal package allows you to deal with decimal numbers without losing
  precision.
repository: https://github.com/a14n/dart-decimal
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  intl: ^0.19.0
  rational: ^2.0.0

dev_dependencies:
  expector: ^0.1.2
  lints: ^2.0.0
  test: ^1.17.2
